### ISSUE TITLE
kanban -setup 

### ISSUE THREAD

**Issue by jaamanu** [jaamanu/Javascript-Capstone-Project#17]
https://github.com/jaamanu/Javascript-Capstone-Project/projects/2

There are two coding partners in this project

**Comment by DammyShittu** [comment]
Hi @jaamanu @AzizRAA,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] This task has no assignee. Kindly fix that.

  ![utn](https://user-images.githubusercontent.com/54848363/197769131-2013544f-ba19-4e71-958a-e9069e5722dc.jpg)

- [ ] There is no task in the template where Student B works on a reservation feature. Kindly remove this task.

  ![nhf](https://user-images.githubusercontent.com/54848363/197769126-a360219f-4d9a-4df1-a89d-f90452b1d0a0.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Wes-Isaac** [comment]
Hi  @jaamanu @AzizRAA,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Kanban board created successfully 👍.
- All cards are assigned 💯.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
